sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/gcloud/
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com > install.sh
  - bash install.sh --disable-prompts
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project misha-babin
  - gcloud config set compute/zone europe-west6-a
  - gcloud container clusters get-credentials multi-k8c
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t michaelbabin/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run michaelbabin/react-test yarn test --watchAll=false
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
